// <auto-generated />
using System;
using BorusanServices.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BorusanServices.Migrations
{
    [DbContext(typeof(BorusanDbContext))]
    partial class BorusanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BorusanServices.Models.Entity.Malzeme", b =>
                {
                    b.Property<string>("MalzemeKodu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MalzemeKodu");

                    b.ToTable("Malzeme");
                });

            modelBuilder.Entity("BorusanServices.Models.Entity.Siparis", b =>
                {
                    b.Property<int>("SistemSiparisNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Agirlik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AgirlikBirim")
                        .HasColumnType("int");

                    b.Property<string>("CikisAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DegisimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("MiktarBirim")
                        .HasColumnType("int");

                    b.Property<string>("MusteriSiparisNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Not")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiparisDurum")
                        .HasColumnType("int");

                    b.Property<string>("VarisAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SistemSiparisNo");

                    b.HasIndex("MalzemeKodu");

                    b.HasIndex("MusteriSiparisNo")
                        .IsUnique();

                    b.ToTable("Siparis");
                });

            modelBuilder.Entity("BorusanServices.Models.Entity.Siparis", b =>
                {
                    b.HasOne("BorusanServices.Models.Entity.Malzeme", "Malzeme")
                        .WithMany("Siparis")
                        .HasForeignKey("MalzemeKodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("BorusanServices.Models.Entity.Malzeme", b =>
                {
                    b.Navigation("Siparis");
                });
#pragma warning restore 612, 618
        }
    }
}
